### ISSUE TITLE
Controllers spawning infinitely during each "Insert Mario"

### ISSUE THREAD

**Issue by NobodyYouKnow01** [libsm64/libsm64-blender#10]
Symptom: I noticed lag while I was working on a level. At the time I only had 3 objects on screen, so I wasn't sure what the issue was. When I opened my command prompt, I had about ten instances of controller.exe open on my system.

Expected behavior: Each time one clicks "Insert Mario," I imagine there'd need to be a check for an instance of the controller already open, and either a reuse or kill for the task already open...

**Comment by jaburns** [comment]
Oh crazy, yeah it should be killing previous ones: https://github.com/libsm64/libsm64-blender/blob/master/input_reader_win.py#L12 I'll see if I can reproduce it on my machine

**Comment by jaburns** [comment]
Going to take a look at this this week.

**Comment by jaburns** [comment]
Fixed in 1.0.5
