### ISSUE TITLE
Addon wont spawn mario [solved... Name of rom needs to match expected name in addon]

### ISSUE THREAD

**Issue by Ponlets** [libsm64/libsm64-blender#16]
![image](https://user-images.githubusercontent.com/101506459/158059086-a6886095-3c32-4c26-bc45-5b38a70fe66c.png)

i have no idea why it wont work 

i have the ROM for the game 

i have blender 3.0 

i have an exceptionally powerful PC 

i have an Xbox one controller plugged in 

i do have the 3d cursor placed above geometry (well on it anyways) 

i even changed the name of the rom to match the expected result for blender and it spat out a different error

![image](https://user-images.githubusercontent.com/101506459/158059436-d9667cb0-1bfa-4c81-9f43-daa5cca5b453.png)

why wont it insert mario 

EDIT: ok so i have downloaded 3 different roms all with no success 

i have no idea why it wont run for me and i am starting to lose my mind ... why wont it just work for me like it does with other people 

why am i stuck over here with errors and no ability to use this addon while everyone else seems to get it working just fine 

WHAT AM I DOING WRONG 

EDITv2 

ok so this addon is SUPER picky about names ... like almost unreasonably so 

the ROM needs to have the SPECIFIC name it is expecting to see then it will work fine

**Comment by SicklyWizard** [comment]
What's the specific name it's looking for?

**Comment by jaburns** [comment]
There might be an issue with paths that contain spaces on windows. That's all I can think of. It's not looking for a specific name, it looks for the ROM at the path you put into that input field. Also the ROM needs to be the one with sha1 checksum 9bef1128717f958171a4afac3ed78ee2bb4e86ce. Glad you got it working, I'll open an issue to verify paths on Windows are working correctly and I'll add the ROM checksum info to the readme.

**Comment by jaburns** [comment]
https://github.com/libsm64/libsm64-blender/issues/24
