### ISSUE TITLE
Unable to move Mario with Switch controller

### ISSUE THREAD

**Issue by B1ad3R3ap3r** [libsm64/libsm64-blender#20]
I am unable to move Mario with a bluetoothed Nintendo switch controller, what controller is this built for?

**Comment by jaburns** [comment]
Currently only XInput devices (Xbox controllers) are supported on Windows, and it seems like support for other controllers is spotty on other platforms as well. I've opened an issue to track additional controller support https://github.com/libsm64/libsm64-blender/issues/23
