### ISSUE TITLE
Support keyboard controls in a non-intrusive fashion

### ISSUE THREAD

**Issue by AnityEx** [libsm64/libsm64-blender#21]
i know this might sound redundant but i love this project and the only way i managed to play with mario is to use keyboard splitter with a bluetooth keyboard playing imputs through bluetooth

**Comment by jaburns** [comment]
I decided not to bother with keyboard support because I figured it would interfere too much with the blender keys. However I'm open to accepting PRs that introduce keyboard controls in a non-intrusive way. I'll leave this issue open for tracking in case someone wants to implement it.

**Comment by UnluckyNinja** [comment]
I have implemented it in a way #25 
It's like using a tool (grab, rotate).
After pressing the "Start" button, it takes over keyboard input and ignore controller input. 
If done playing then press "ESC" to stop.

![image](https://user-images.githubusercontent.com/1270155/158541289-29c94c7b-33f7-41a6-8458-e9ad5f50d5b3.png)
