### ISSUE TITLE
Viewport is centered below Mario's feet, which makes it hard to see where you are going.

### ISSUE THREAD

**Issue by JamesO2x** [libsm64/libsm64-blender#27]
Title says it all, really. When the "**Follow Mario with 3D Cursor + Camera**" option is toggled on, the view is pointed exactly at Mario's origin (_right below his feet_). This makes it hard to see anything if the view is zoomed in at all. 

I understand that Mario's origin is below his feet, as this is how Mario 64 is programmed. And I understand that the 3D Cursor just snaps to his origin, and the Blender viewport is then centered on that 3D cursor.

## Relevant image:
![Can't See](https://i.imgur.com/PGd3Vle.png)

# But would it be possible to either place the 3D cursor above his head during play, or even just offset the Z-location of the viewport center from the 3D cursor?

I suggest that the viewport should be placed **above Mario's head** and not just centered at his body. If the viewport is looking at a point above Mario's head, then Mario's model won't ever be obstructing our view. And if you zoom in all the way you could have a sort of "First Person" mode.

## Here's some images that show where I would suggest the 3D cursor/viewport camera be centered in relation to Mario.
You can see here that even if you zoom in very far, you can still see where you are going:
![Suggestion](https://i.imgur.com/TZamGcK.png)
![Zoomed](https://i.imgur.com/JzLzqwL.png)

---

## Alternatively, having a new **option** to offset the view would be nice. Here's a suggestion of how I would modify the panel to do this:
![Panel](https://i.imgur.com/LSEr0Hu.png)

I guess the `X` and `Y` slider's aren't that important, mainly just the `Z` one. But I just mocked up all 3 as an example of how it could look.

**Comment by JamesO2x** [comment]
No problem. Thanks for this cool addon, I've been addicted to playing with it for a few days now, haha.

**Comment by jaburns** [comment]
Thanks for the fix!
