### ISSUE TITLE
I get a error trying to load mario

### ISSUE THREAD

**Issue by Sushi8756** [libsm64/libsm64-blender#30]
![image](https://user-images.githubusercontent.com/90991195/162329095-5839997d-a460-4bdd-9907-e950336cf3c2.png)

I am using ubuntu, I have fast64 and the rom file, but I get this error. How do I fix?

**Comment by Agent-11** [comment]
GLIBC not found

**Comment by Sushi8756** [comment]
> GLIBC not found

Ok so what do I do?

**Comment by jaburns** [comment]
I've run into this on some machines and it's annoying that the library depends on a specific glibc version. It would be possible to statically link against musl or something and not have this problem anymore. I'll open an issue to solve that, but in the meantime you'll have to look up how to install and use different glibc versions on your distribution.

**Comment by jaburns** [comment]
Actually @Sushi8756 the easiest way to fix this is to build libsm64 on your machine and copy the generated .so file into libsm64-blender.  libsm64 is very easy to build and it will link your system's glibc, so it should work fine that way.

**Comment by jaburns** [comment]
Version 1.0.6 should fix this issue.
