### ISSUE TITLE
Support for keyframing/recording Mario

### ISSUE THREAD

**Issue by guighub** [libsm64/libsm64-blender#36]
This is an amazing tool, but will there be support for recording keyframes of Mario? It doesn't seem like he has a rig, so I'm assuming it's just geometry being imported every frame from the library. Maybe there's a way to place a new mesh of Mario every frame instead of removing his previous geometry, and then enabling and disabling each frame accordingly without lagging too much?

**Comment by jaburns** [comment]
Definitely planned, would be a really cool feature: https://github.com/libsm64/libsm64-blender/issues/13
(Closing as dupe)

**Comment by TheBob121212** [comment]
how do I key frame mario?
