### ISSUE TITLE
Cannot Add SM64 Rom

### ISSUE THREAD

**Issue by aRandomShyGuy** [libsm64/libsm64-blender#48]
Sorry if this is stupid, I'm new to Blender but I was watching a tutorial on how to use this and it said to click the folder button next to the button on where the for the SM64 rom is but the folder and where the path is sourced button isn't appearing and I'm confused and can't insert the rom.

**Comment by aRandomShyGuy** [comment]
Yeah.

**Comment by aRandomShyGuy** [comment]
Sorry I was tired, I wrote this poorly, the button that you're supposed to click to insert the rom isn't there and I don't know what to do.

**Comment by jaburns** [comment]
Can you share a screenshot of what the panel for the plugin looks like on your machine?

**Comment by jaburns** [comment]
Does it look like the one shared in this issue? https://github.com/libsm64/libsm64-blender/issues/44

**Comment by jaburns** [comment]
Closing as abandoned.
