### ISSUE TITLE
Cant control blender UI when using keyboard

### ISSUE THREAD

**Issue by gdandsm64fan123** [libsm64/libsm64-blender#49]
I cant use the blender ui when im using the keyboard to control mario. And i couldnt delete the LibSM64 Mario object.

**Comment by TheoCGaming** [comment]
what version of blender are you using

**Comment by gdandsm64fan123** [comment]
Im using Blender 3.6 which i think its the latest version there is as of right now.

**Comment by ExtCan** [comment]
When you enable Keyboard controls you lose control of the UI, I believe this is a purposeful feature, as the keys you use to control Mario are also shortcuts to tools and such, I believe this was done to remove the chance of accidental mishaps. There is no way to disable this afaik. To exit Mario mode, press the escape (esc) key.

**Comment by gdandsm64fan123** [comment]
closed i already know
