### ISSUE TITLE
Mario isn't there

### ISSUE THREAD

**Issue by JalvinGaming** [libsm64/libsm64-blender#50]
[SOLVED] In this program, even though I have a ROM with the EXACT checksum required, Mario just doesn't exist. All I can see is the little 3D cursor following him. How can I fix this issue?

Solution: I was using the 4.0 beta.

**Comment by Hri7566** [comment]
is that *really* a solution, though?

**Comment by home-gihub** [comment]
i cant see mine

**Comment by jaburns** [comment]
I guess it doesn't work with Blender 4.0. Just made a ticket for doing that specifically. https://github.com/libsm64/libsm64-blender/issues/51

**Comment by dave41413** [comment]
![image](https://github.com/libsm64/libsm64-blender/assets/162748837/8b8300d1-ce09-4b1b-920a-ed08562a72a2)

**Comment by dave41413** [comment]
![image](https://github.com/libsm64/libsm64-blender/assets/162748837/579a6fe4-f3ac-4459-bab8-d514b76ea604)
